syntax = "proto3";

package contracts.core.coaching.v1.event;

option go_package = "github.com/viethung213/gym-companion/internal/gen/go/contracts/core/coaching/v1/event;coachingv1event";

import "google/protobuf/timestamp.proto";
import "contracts/core/coaching/v1/message/coaching_messages.proto";

message RoadmapInitiatedEventPayload {
  string roadmap_id = 1;
  string user_id = 2;
  google.protobuf.Timestamp initiated_at = 3;
  contracts.core.coaching.v1.message.Roadmap roadmap = 4;
}

message RoadmapAdjustedEventPayload {
  string roadmap_id = 1;
  string user_id = 2;
  string reason = 3;
  google.protobuf.Timestamp adjusted_at = 4;
  contracts.core.coaching.v1.message.Roadmap roadmap = 5;
}

message SessionPlanExecutedEventPayload {
  string session_plan_id = 1;
  string roadmap_id = 2;
  string user_id = 3;
  google.protobuf.Timestamp executed_at = 4;
  float session_scr = 5;
  float session_delta_rpe = 6;
}
