name: GolangCI-Lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Generate golangci-lint Config
        run: |
          cat << 'EOF' > .golangci.yml
          run:
            timeout: 5m
            issues-exit-code: 1
            tests: true

          linters:
            disable-all: true
            enable:
              - govet
              - errcheck
              - gocritic
              - errorlint
              - errname
              - forcetypeassert
              - gochecknoglobals
              - gochecknoinits
              - forbidigo
              - sigchanyzer
              - musttag
              - perfsprint
              - prealloc
              - lll
              - decorder
              - gci
              - revive
              - gofmt
              - goprintffuncname
              - paralleltest

          linters-settings:
            govet:
              enable-all: true
              disable:
                - fieldalignment # Tắt cảnh báo sắp xếp trường struct để tránh tối ưu hoá mù quáng
            lll:
              line-length: 99 # Giới hạn 99 ký tự theo Rule 38
            gocritic:
              enabled-tags:
                - diagnostic
                - style
                - performance
            forbidigo:
              forbid:
                - '^os\.Exit$#Chỉ cho phép os.Exit trong main() của package main'
                - '^log\.Fatal$#Chỉ cho phép log.Fatal trong main() của package main'
                - '^log\.Fatalf$#Chỉ cho phép log.Fatalf trong main() của package main'
          EOF

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
